version: '3'
volumes:
  postgres_data:
    driver: local
services:
  # Database For Local Testing Only
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password